// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD60Smd5D1g_kFzGWgzSkBuXbth_p1VesY',
    appId: '1:730396874674:web:a3e75e838cf898699036ab',
    messagingSenderId: '730396874674',
    projectId: 'ecommerce-ea02d',
    authDomain: 'ecommerce-ea02d.firebaseapp.com',
    storageBucket: 'ecommerce-ea02d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApgXm6OxQ8EUg5cb9yQoGrkQqLUYR_d_k',
    appId: '1:730396874674:android:0cb50fed2b110a789036ab',
    messagingSenderId: '730396874674',
    projectId: 'ecommerce-ea02d',
    storageBucket: 'ecommerce-ea02d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuE2wLPijOl67lDtX14yo_8nyqXSuef_k',
    appId: '1:730396874674:ios:5aa0ad6f6617a7c19036ab',
    messagingSenderId: '730396874674',
    projectId: 'ecommerce-ea02d',
    storageBucket: 'ecommerce-ea02d.appspot.com',
    iosBundleId: 'com.example.projectapp',
  );
}
